### ISSUE TITLE
[MC v1.21] Replace Treasure Key item "Tripwire Hook" with new "Trial Key"

### ISSUE THREAD

**Issue by dennishzg** [UltraCosmetics/UltraCosmetics#154]
### Describe the feature and how it would be used

A new item will be added in the next major Minecraft update v1.21. The "Trial Key" is a perfect replacement for the "Tripwire Hook" item that we currently use for the Treasure Keys. The main menu and buy-key menu should show the new "Trial Key" if you use Minecraft >= v1.21.

![Screenshot (60)](https://github.com/datatags/UltraCosmetics/assets/33426785/61a6a596-6e47-4f42-97c0-efb528015553)

### Are there alternatives?

/

**Comment by datatags** [comment]
I forgot that the item has the tooltip "Disabled item" in 1.20.6 since you need the experimental pack for it, so I think this will need to wait until actual 1.21 or until I can figure out a way to just check if the item is enabled
