### ISSUE TITLE
Hungarian language support

### ISSUE THREAD

**Issue by lackooka** [UltraCosmetics/UltraCosmetics#181]
### Describe the feature and how it would be used

Add hungarian language file if you can please, because we tried to change messages and automatically reset the file back to english.

### Are there alternatives?

-

**Comment by datatags** [comment]
UltraCosmetics has a hungarian translation file, but as you saw it's only 4% translated currently. I don't know hungarian so I can't really assist, but if you are willing to help translate, you can do so here on Crowdin: https://crowdin.com/project/ultracosmetics
