### ISSUE TITLE
Cannot run on 1.21

### ISSUE THREAD

**Issue by CaesarGalahad** [UltraCosmetics/UltraCosmetics#321]
### Check if the issue is fixed in dev builds

- [X] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

Unable to load plugin

### What was supposed to happen?

plugin should be loaded

### What happened instead?

Unable to load plugin

### What version of UltraCosmetics are you using? Do not say 'latest'.

UltraCosmetics-3.7-DEV-b2

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

PurPur 2276 MC-1.21

### What plugins do you have installed?

[Plugins.txt](https://github.com/user-attachments/files/16428069/Plugins.txt)

### Are there any errors in the console or in logs?

[Log.txt](https://github.com/user-attachments/files/16428072/Log.txt)

https://mclo.gs/Ghrwoes

**Comment by datatags** [comment]
Hello, this is not a bug, the issue appears to be that your server doesn't have an internet connection, and UC requires an internet connection to download its libraries. Connect your server to the internet just once and the issue will be resolved. If you have any other questions, [Discord](https://discord.gg/PgSXZT37JV) is a better place for support
