### ISSUE TITLE
Duplication of the Discoball gadget (Beacon item)

### ISSUE THREAD

**Issue by cosmunn** [UltraCosmetics/UltraCosmetics#345]
### Check if the issue is fixed in dev builds

- [X] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

1. Equip Discoball gadget
2. Place the beacon on an armor stand with arms
3. Take it from the armor stand on a different inventory slot than the Gadget-Slot
4. Place it on the ground
5. Repeat

### What was supposed to happen?

Preferably it should either not allow me to place any gadget on an armor stand, or cancel the block place event if I do try to place it from a slot other than the Gadget-Slot.

### What happened instead?

I can take the Beacon item from the armor stand into a different slot than the Gadget-Slot, and place it on the ground. I can repeatedly equip the gadget and repeat it as many times as I'd like.

### What version of UltraCosmetics are you using? Do not say 'latest'.

UltraCosmetics-3.7-RELEASE

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

Purpur Version: 1.21-2284-4e55e26 (MC: 1.21)

### What plugins do you have installed?

Paper Plugins: (7):
AdvancedServerList, AntiRedstoneClock-Remastered, FancyHolograms, HuskHomes, PaperTweaks, SpectatorPlus, TreasureMapsPlus
Bukkit Plugins: (111):
AdvancedSensitiveWords, AFKPlus, AFKPlusPAPI, ajLeaderboards, AngelChest, AnnouncerPlus, AxInventoryRestore, AxiomPaper, AxTrade, BetterGUI, BetterTridents, ChestSort, Chunky, ChunkyBorder, Citizens, ConditionalEvents, ConsoleSpamFix, ControlPlayer, CoreProtect, CrazyAdvancementsAPI, DecentHolograms, DiscordRoleSync, DiscordSRV, DiscordSRVUtils, DoorsReloaded, DropHeads, emotecraft, EntityDetection, ExtraContexts, FarmControl, FastAsyncWorldEdit, floodgate, FreedomChat, Geyser-Recipe-Fix, Geyser-Spigot, GeyserExtras, *GPAccruals, GPClaimExpiration, GPExtension, GPFlags, GriefPrevention, GSit, HarderDespawn, Hat, HsRails, Hurricane, HuskHomesGUI-bt, ImageFrame, Insights, InteractiveChat, JumpPad, LastLoginAPI, LevelledMobs, LibertyBans, LuckPerms, LunaticFamily, LunaticLib, Maintenance, ManyMobs, MinecartTrains, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MyCommand, NBTAPI, nChat, Nerfstick, *Nick-bt, nLogin, OpenInv, OreAnnouncer, PetNameFix, PhantomGuard, PlaceholderAPI, PlasmoVoice, PlayerKits2, PlugManX, PortableCraftingInvs, ProtocolLib, PurpurExtras, pv-addon-broadcast, pv-addon-discs, pv-addon-groups, pv-addon-lavaplayer-lib, pv-addon-priority, pv-addon-sculk, pv-addon-whisper, PvPManager, ReElytras, Sentinel, ServerVariables, SimpleClans, SimpleFly, SkinsRestorer, sleep-most, StreamingDrops, SuperVanish, TAB, TAB-Additions, TreeAssist, UltimateAutoRestart, UltraCosmetics, Vault, ViaBackwards, ViaVersion, ViaVersionStatus, VillagerOptimizer, Vulcan, WorldGuard, WorldGuardExtraFlags, XConomy

**Comment by cosmunn** [comment]
[Here's a video showcasing the issue](https://youtu.be/WjsiDCjHLi0), if it's of any help.

**Comment by cosmunn** [comment]
Would like to add that this applies to every gadget that has an item as a block. Includes the melonthrower, tnt, ghostparty, freezecannon, colorbomb, trampoline, blackhole and blizzardblaster

**Comment by datatags** [comment]
Fixed in 2b4cd8eda9239f41c32f27d3db1e2432392c9574
