### ISSUE TITLE
Pet "allay" failed to load (maybe)

### ISSUE THREAD

**Issue by LOURENT4462** [UltraCosmetics/UltraCosmetics#351]
### Check if the issue is fixed in dev builds

- [X] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

1. Run cmd `/uc toggle pets allay`
2. Message: Invalid Pet

### What was supposed to happen?

Pet allay should be spawned

### What happened instead?

Pet allay failed to spawn(instead giving invalid pet message)

### What version of UltraCosmetics are you using? Do not say 'latest'.

3.7-RELEASE

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

This server is running Paper version 1.21-124-master@df3b654 (2024-08-02T00:02:38Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### What plugins do you have installed?

-

### Are there any errors in the console or in logs?

nope

### Additional information that could be helpful in fixing the problem

Allay configuration at `config.yml`
![Screenshot (231)](https://github.com/user-attachments/assets/d7200f14-00f3-43db-85b6-bdfefbc0383c)

Pet allay cmd suggestion doesn't appear
![Screenshot (233)](https://github.com/user-attachments/assets/6060a962-65ee-4629-82f8-cd2cbd05d1a9)

**Comment by LOURENT4462** [comment]
> > I have confirmed that the issue is present on the latest dev build
> 
> Did you actually? This should already be fixed

ohh.. that's good... i didn't find the dev build download link t-t

**Comment by datatags** [comment]
https://github.com/UltraCosmetics/UltraCosmetics/releases
