### ISSUE TITLE
Cannot work on Leaf 1.21.1

### ISSUE THREAD

**Issue by CaesarGalahad** [UltraCosmetics/UltraCosmetics#375]
### Check if the issue is fixed in dev builds

- [X] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

Cannot work on Leaf 1.21.1
 
Server INFO
UltraCosmetics version 3.8-DEV-b1
Server version Leaf 1.21.1-DEV-ver/1.21.1@5cb2cb6

Log INFO
https://mclo.gs/0YBFfVn

### What was supposed to happen?

It should be able to load normally

### What happened instead?

Cannot work on Leaf 1.21.1

### What version of UltraCosmetics are you using? Do not say 'latest'.

UltraCosmetics-3.8-DEV-b1

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

Leaf 1.21.1-DEV-ver/1.21.1@5cb2cb6

### What plugins do you have installed?

[目录.txt](https://github.com/user-attachments/files/17074103/default.txt)

### Are there any errors in the console or in logs?

https://mclo.gs/0YBFfVn

**Comment by datatags** [comment]
Already fixed in 359283f0488faee11986458d9893695c146abe81
